TARGET_NAME
    GTest_TestWrapper
LIBRARY_TYPE
    INTERFACE #SHARED    
INTERFACE_DEPENDS 
    GTest::gtest
    GTest::gtest_main
INTERFACE_COMPILE_FEATURES
    c++17
#GENERATE_EXPORT_HEADER
#PROPERTIES
#    LINKER_LANGUAGE CXX
#SOURCES
#    src/dummy.cpp