set(CMAKECS_TARGET_OPTIONS "EXECUTABLE;NO_TARGET_EXPORT;AUTO_GLOB_SOURCE;AUTO_GLOB_INCLUDE;GENERATE_EXPORT_HEADER" CACHE INTERNAL "")
set(CMAKECS_TARGET_ARGS "TARGET_NAME;LIBRARY_TYPE;EXECUTABLE_TYPE" CACHE INTERNAL "")
set(CMAKECS_TARGET_MULTI_ARGS "PUBLIC_SOURCES;PRIVATE_SOURCES;INTERFACE_SOURCES;SOURCES"
                              "PRIVATE_DEPENDS;PUBLIC_DEPENDS;INTERFACE_DEPENDS"
                              "PUBLIC_DEFINITIONS;PRIVATE_DEFINITIONS;INTERFACE_DEFINITIONS"
                              "PUBLIC_COMPILE_OPTIONS;PRIVATE_COMPILE_OPTIONS;INTERFACE_COMPILE_OPTIONS"
                              "PUBLIC_COMPILE_FEATURES;PRIVATE_COMPILE_FEATURES;INTERFACE_COMPILE_FEATURES"
                              "PROPERTIES"
                              "PUBLIC_INCLUDE_DIRECTORIES;PRIVATE_INCLUDE_DIRECTORIES;INTERFACE_INCLUDE_DIRECTORIES"
                              "PUBLIC_LINK_OPTIONS;PRIVATE_LINK_OPTIONS;INTERFACE_LINK_OPTIONS"
                              "PUBLIC_PRECOMPILE_HEADERS;PRIVATE_PRECOMPILE_HEADERS;INTERFACE_PRECOMPILE_HEADERS"
                              "REUSE_PRECOMPILE_HEADERS_FROM_TARGETS"
                              "HEADERS;HEADER_DIRECTORIES_TO_INSTALL" CACHE INTERNAL "")




